// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails

import "jquery"
import "@hotwired/turbo-rails"
import "controllers"


// import "template-js/chart-utils"
// import "chartjs-plugin-zoom"
// import "events-data"
// import "functions.bundle"
// import "functions"
// import "holder"
// import "jquery.calendario"
// import "jquery.hotspot"
// import "jquery"
// import "jquery.mousewheel"
// import "plugins.bootstrap"
// import "plugins.carousel"
// import "plugins.clipboard"
// import "plugins.cookie"
// import "plugins.countdown"
// import "plugins.dribble"
// import "plugins.easing"
// import "plugins.fitvids"
// import "plugins.flexslider"
// import "plugins.flickrfeed"
// import "plugins.form"
// import "plugins.gmap"
// import "plugins.hashchange"
// import "plugins.imagesloaded"
// import "plugins.infinitescroll"
// import "plugins.isotope"
// import "plugins.jpaginate"
// import "plugins"
// import "plugins.lazyload"
// import "plugins.lightbox"
// import "plugins.min.js"
// import "plugins.packery"
// import "plugins.parallax"
// import "plugins.piechart"
// import "plugins.prism"
// import "plugins.stickysidebar"
// import "plugins.swiper"
// import "plugins.textrotator"
// import "plugins.youtube"

import "bootstrap"
